server:
  port: 8082
spring:
  application:
    name: service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
        extension-configs:
          - data-id: service.yml
            group: DEFAULT_GROUP
            refresh: true
        refresh-enabled: true
